### ISSUE TITLE
Would you please port it to 1.18.2 Fabric, thanks

### ISSUE THREAD

**Issue by ardissaps** [AlurienFlame/Balanced-Recall#1]

**Comment by AlurienFlame** [comment]
Only because you asked so nicely. 🙂 Version [1.0.2+1.18.2](https://github.com/AlurienFlame/Balanced-Recall/releases/tag/1.0.2%2B1.18.2) should work on 1.18.2.

**Comment by ardissaps** [comment]
> Only because you asked so nicely. 🙂 Version [1.0.2+1.18.2](https://github.com/AlurienFlame/Balanced-Recall/releases/tag/1.0.2%2B1.18.2) should work on 1.18.2.

Thank you very much sir!
