### ISSUE TITLE
Could you mark the 1.19 version as compatible with 1.19.1 and 1.19.2 please?

### ISSUE THREAD

**Issue by Constantine415** [AlurienFlame/Balanced-Recall#2]
I am unable to add the mod to a server because of its supposed incompatibility in versions.

**Comment by AlurienFlame** [comment]
Weird, the `fabric.mod.json` sets it as compatible with any 1.19 version. Won't be able to take a look at this for several months, but you're free to take a crack at fixing it if you want. Version compatibility issues are usually just a matter of changing a config file and rebuilding the project.

**Comment by AlurienFlame** [comment]
Guess I never got around to this, sorry. I don't maintain old versions.
